"""rename department

Revision ID: cdd638ffb413
Revises: 5de0c77daa8d
Create Date: 2024-06-25 12:33:31.136112

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdd638ffb413'
down_revision = '5de0c77daa8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department','departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table("departments", "department",)
    # ### end Alembic commands ###
